version: "3.9"

services:
  db:
    build: .
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - POSTGRES_DB=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: db
    restart: always
    ports:
      - "5432:5432"


  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db